trigger:
  branches:
    include:
    - main

pool: 
  vmImage: ubuntu-latest

variables: 
  rsgroup: 'tfstate'
  backServiceArm: 'DevServiceConnection' 
  storageaccount: 'storagedesafiotf' 
  containername: 'tfstate' 
  key: 'azuredevops.tfstate'

stages:
  - stage: 'Instalando_Terraform'
    jobs:
      - job: 'instalandoterraform'
        steps:
        - task: TerraformInstaller@1
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: 'latest'

  - stage: 'Init_Terraform'
    dependsOn: 
      - 'Instalando_Terraform'
    jobs:
      - job: 'terraforminit'
        steps:
        - task: TerraformTaskV4@4
          displayName: 'Init Terraform'
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: '$(backServiceArm)'
            backendAzureRmResourceGroupName: '$(rsgroup)'
            backendAzureRmStorageAccountName: '$(storageaccount)'
            backendAzureRmContainerName: '$(containername)'
            backendAzureRmKey: '$(key)'
  
  - stage: 'Validando'
    dependsOn: 
      - 'Init_Terraform'
    jobs:
      - job: 'Validando'
        steps:
          - task: TerraformTaskV4@4
            displayName: 'Validando'
            inputs:
              provider: 'azurerm'
              command: 'validate'
  
  - stage: 'Terrafom_Plan'
    dependsOn: 
      - 'Validando'
    jobs:
      - job: 'plan'
        steps:
        - task: TerraformTaskV4@4
          displayName: 'Terraform Plan'
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceName: '$(backServiceArm)'
            commandOptions: '-out=tfplan'
  
  - stage: 'Terraform_Apply'
    dependsOn: 
      - 'Terrafom_Plan'
    jobs:
      - job: 'Apply'
        steps:
        - task: TerraformTaskV4@4
          displayName: 'Terraform Apply'
          inputs:
            command: 'apply'
            environmentServiceName: '$(backServiceArm)'
            commandOptions: '-auto-approve -input=false tfplan'