trigger:
  branches:
    include:
    - main

pool: 
  vmImage: ubuntu-latest

variables: 
  rsgroup: 'tfstate'
  backServiceArm: 'DevServiceConnection' 
  storageaccount: 'storagedesafiotf' 
  containername: 'tfstate' 
  key: 'azuredevops.tfstate'

stages:
  - stage: build_and_test
    jobs:
    - job: "show_subscription_and_show_current_dir"
      steps:
      - script: |
          az login --service-principal -u  $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID) && az account list
        displayName: 'show subscription'
      - script: pwd && ls -ltra && env
        displayName: 'show current dir'
  - stage: 'Instalando_Terraform'
    jobs:
      - job: 'instalandoterraform'
        steps:
        - task: TerraformInstaller@1
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: 'latest'

  - stage: 'Init_Terraform'
    dependsOn: 
      - 'Instalando_Terraform'
    jobs:
      - job: 'terraforminit'
        steps:
        - task: TerraformTaskV4@4
          displayName: 'Init Terraform'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(Build.SourcesDirectory)'
            backendType: 'azurerm'
            ensureBackend: true
            backendServiceArm: 'DevServiceConnection'
            backendAzureRmResourceGroupName: '$(rsgroup)'
            backendAzureRmStorageAccountName: '$(storageaccount)'
            backendAzureRmContainerName: '$(containername)'
            backendAzureRmKey: '$(key)'
  
  - stage: 'Validando'
    dependsOn: 
      - 'Init_Terraform'
    jobs:
      - job: 'Validando'
        steps:
          - task: TerraformTaskV4@4
            displayName: 'Validando'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(Build.SourcesDirectory)'
  
  - stage: 'Terrafom_Plan'
    dependsOn: 
      - 'Validando'
    jobs:
      - job: 'plan'
        steps:
        - task: TerraformTaskV4@4
          displayName: 'Terraform Plan'
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(Build.SourcesDirectory)'
            environmentServiceName: '$(backServiceArm)'
            commandOptions: '-out=tfplan'
  
  - stage: 'Terraform_Apply'
    dependsOn: 
      - 'Terrafom_Plan'
    jobs:
      - job: 'Apply'
        steps:
        - task: TerraformTaskV4@4
          displayName: 'Terraform Apply'
          inputs:
            command: 'apply'
            workingDirectory: '$(Build.SourcesDirectory)'
            environmentServiceName: '$(backServiceArm)'
            commandOptions: '-auto-approve -input=false tfplan'